services:
  db:
    image: postgres:15
    container_name: polling-postgres
    environment:
      POSTGRES_DB: dbhabit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Berik2006
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - polling-network

  backend:
    image: polling-backend:latest
    container_name: polling-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dbhabit?currentSchema=srefinal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Berik2006
    depends_on:
      - db
    networks:
      - polling-network

  frontend:
    image: polling-frontend:latest
    container_name: polling-frontend
    ports:
      - "3030:80"
    networks:
      - polling-network

volumes:
  postgres-data:

networks:
  polling-network:
    external: true
    name: polling-network