name: Polling-App CI/CD

on:
  push:
    branches: [ main, master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run frontend tests and build
        working-directory: polling-app-client
        run: |
          npm install
          npm test -- --watchAll=false
          npm run build

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Run backend tests and build
        working-directory: polling-app-server
        run: |
          chmod +x ./mvnw
          ./mvnw clean install
      
